# Generated by Django 4.1.1 on 2023-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KittyCats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=200)),
                ("missing", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
                ("user", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("animal", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
