# Generated by Django 4.1.1 on 2022-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittycats",
            name="img",
            field=models.ImageField(upload_to="image_of_cats"),
        ),
    ]
