# Generated by Django 4.1.1 on 2023-01-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittycats",
            name="animal",
            field=models.CharField(
                choices=[
                    ("Dog", "Dog"),
                    ("Cat", "Cat"),
                    ("Bird", "Bird"),
                    ("Rabbit", "Rabbit"),
                    ("Guinea Pig", "Guinea Pig"),
                    ("Fish", "Fish"),
                    ("Reptile", "Reptile"),
                    ("Ferret", "Ferret"),
                    ("Stick Insect", "Stick Insect"),
                    ("Rat", "Rat"),
                    ("Mouse", "Mouse"),
                    ("Amphibian", "Amphibian"),
                    ("Farm Animal", "Farm Animal"),
                    ("Other", "Other"),
                ],
                max_length=200,
            ),
        ),
    ]
