# Generated by Django 4.1.1 on 2022-12-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_kittycats_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittycats",
            name="img",
            field=models.ImageField(upload_to=""),
        ),
    ]
