# Generated by Django 4.1.1 on 2022-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_kittycats_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittycats",
            name="user",
            field=models.CharField(max_length=200),
        ),
    ]
