# Generated by Django 3.2.7 on 2021-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='KittyCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('contact', models.TextField()),
                ('owner', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUsers',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
