# Generated by Django 3.2.7 on 2021-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211112_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kittycats',
            old_name='owner',
            new_name='missing',
        ),
    ]
