# Generated by Django 4.1.1 on 2022-12-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_kittycats_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittycats",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
