# Generated by Django 4.1.1 on 2022-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_kittycats_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittycats",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
