# Generated by Django 3.2.7 on 2021-11-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_owner_kittycats_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kittycats',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
